version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: pradsanyal/aws-lightsail-app:latest
    image: aws-lightsail-app:latest
    ports:
      - "8080:8080" 
    restart: unless-stopped
    depends_on: 
      - redis 
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379    
    networks: 
      - backend
      
  # Redis Service   
  redis:
    image: "redis:alpine" 
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:    