version: 2

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
       - checkout
       - setup_remote_docker
       - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            docker tag pradsanyal/aws-lightsail-app:latest pradsanyal/aws-lightsail-app:1.0.$CIRCLE_BUILD_NUM
            docker images
            # login to docker hub
            echo $DOCKER_PASSWORD	 | docker login -u $DOCKER_USER --password-stdin
            docker push --all-tags pradsanyal/aws-lightsail-app
       - run:
          name: install awscli
          command: |
            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt install python3-pip
            python3 -m pip3 install awscliv2
            aws lightsail 
      #  - run:
      #     name: Install Lightsail Control CLI
      #     command: |
      #       curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      #       brew install aws/tap/lightsailctl
  

          
# workflows:
#   version: 2
#   build:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           context: aws