version: 2

orbs:
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build:
    executor: aws-cli/default
    steps:
       - checkout
       - setup_remote_docker
       - aws-cli/setup:
          profile-name: default
          context: aws
       - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            docker tag pradsanyal/aws-lightsail-app:latest pradsanyal/aws-lightsail-app:1.0.$CIRCLE_BUILD_NUM
            docker images
            # login to docker hub
            echo $DOCKER_PASSWORD	 | docker login -u $DOCKER_USER --password-stdin
            docker push --all-tags pradsanyal/aws-lightsail-app
       - run:
          name: Install Lightsail Control CLI
          command: brew install aws/tap/lightsailctl
