version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
  

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
       - checkout
       - setup_remote_docker
       - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            docker tag pradsanyal/aws-lightsail-app:latest pradsanyal/aws-lightsail-app:1.0.$CIRCLE_BUILD_NUM
            docker images
            # login to docker hub
            echo $DOCKER_PASSWORD	 | docker login -u $DOCKER_USER --password-stdin
            docker push --all-tags pradsanyal/aws-lightsail-app
       - run:
          name: Install python
          command: |
            sudo apt-get update
            if ! [ -x "$(which python3)" ]; then
            sudo apt-get -y install python3
            fi
            if ! [ -x "$(which pip3)" ]; then
            sudo apt-get -y install python3-pip
            fi
      #  - aws-cli/install
       - aws-cli/setup:
          profile-name: default
       - run: 
          name: get aws lightsail container service
          command: |
            aws lightsail get-container-services
       - run: 
          name: push image to aws lightsail 
          command: |
           sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
           sudo chmod +x /usr/local/bin/lightsailctl 
           aws lightsail push-container-image --region us-east-1 --service-name aws-lightsail-app --label python-app --image aws-lightsail-app:latest
workflows:
  deploy-to-lightsail:
    jobs:
      - build:
          context: aws