version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
  

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
       - checkout
       - setup_remote_docker
       - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            docker tag pradsanyal/aws-lightsail-app:latest pradsanyal/aws-lightsail-app:1.0.$CIRCLE_BUILD_NUM
            docker images
            # login to docker hub
            echo $DOCKER_PASSWORD	 | docker login -u $DOCKER_USER --password-stdin
            docker push --all-tags pradsanyal/aws-lightsail-app
       - run:
          name: Install python
          command: |
            sudo apt-get update
            if ! [ -x "$(which python3)" ]; then
            sudo apt-get -y install python3
            fi
            if ! [ -x "$(which pip3)" ]; then
            sudo apt-get -y install python3-pip
            fi
       - aws-cli/install
      #  - run:
      #     name: Install Lightsail Control CLI
      #     command: |
      #       curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      #       brew install aws/tap/lightsailctl
  

          
# workflows:
#   version: 2
#   build:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           context: aws