version: 2

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
       - checkout
       - setup_remote_docker
       - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            docker tag pradsanyal/aws-lightsail-app:latest pradsanyal/aws-lightsail-app:1.0.$CIRCLE_BUILD_NUM
            docker images
            # login to docker hub
            echo $DOCKER_PASSWORD	 | docker login -u $DOCKER_USER --password-stdin
            docker push --all-tags pradsanyal/aws-lightsail-app
       - run:
          name: Install Lightsail Control CLI
          command: brew install aws/tap/lightsailctl
  
  deploy:
    docker:
      - image: cimg/python:3.10.1
    resource_class: small
    steps:
      - aws-cli/setup:
          profile-name: default
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: aws