version: 2

orbs:
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
       - checkout
       - setup_remote_docker
       - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            docker tag aws-lightsail-app:latest aws-lightsail-app:1.0.$CIRCLE_BUILD_NUM
            # login to docker hub
            echo $DOCKER_PASSWORD	 | docker login -u $DOCKER_USER --password-stdin
            docker push pradsanyal/aws-lightsail-app:1.0.$CIRCLE_BUILD_NUM